### ISSUE TITLE
Auto-completion of model names doesn't work after recompiling the project

### ISSUE THREAD

**Issue by Fastfinguh** [jbanquo/chaturbate-downloader-v2#2]
I get the drop down menu of all the models if I use your precompiled v2.0.0-beta.3 version.

I wanted to add more models in so I downloaded the .sln. After I try to (re)compile the code the drop down menu for models doesn't appear anymore. Am I doing something wrong, or what should I do to make the drop down menu appear?

Edit: https://imgur.com/oHuoxsX - Here's a screenshot

**Comment by jbanquo** [comment]
Make sure the file is alphabetically sorted. There's a nice visual studio code plugin you can use for this - https://marketplace.visualstudio.com/items?itemName=Tyriar.sort-lines

**Comment by Fastfinguh** [comment]
Works like a charm now. Thank you for your help!
