### ISSUE TITLE
Connecting/Disconnecting - Constantly

### ISSUE THREAD

**Issue by Mush-r00m** [jbanquo/chaturbate-downloader-v2#3]
I have streamlink installed & its in the system path.
I have tried with dozens of models but it constantly says Connecting then diconnected
Never downloads any videos.

Any advice?
v2.0.0-beta.3

**Comment by jbanquo** [comment]
Are you able to manually open streams through the commandline, using streamlink?

**Comment by Mush-r00m** [comment]
No clue how to do that on windows. I installed streamlink, made sure it was in the system path.
Unzipped v2.0.0-beta.3 ran cb-downloader-v2.exe  added live models and it says  Connecting then diconnected constantly.

Edit: i tried to open a chatubate url via cmd. Says: No plugin can handle the URL
so perhaps i dont have the plugin you provided in the corrrect directory. I left it in the unziped foler with your program

**Comment by jbanquo** [comment]
You need to copy that file into, e.g. `C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugins\`
This is now a streamlink issue so I will be closing this.
